### ISSUE TITLE
Gitbook link in readme is broken

### ISSUE THREAD

**Issue by arjunattam** [100mslive/100ms-ios#6]
This section: https://github.com/100mslive/100ms-ios#token-generation

**Comment by ygit** [comment]
@arjunattam This repo is not maintained anymore. 
https://github.com/100mslive/100ms-ios-sdk is the v2 & current version of 100ms iOS SDK

**Comment by arjunattam** [comment]
understood. can we make that obvious - in the readme, or by archiving the repo?

I landed here by changing "android" to "ios" when I was on `https://github.com/100mslive/100ms-android` and there was nothing to tell me that this repo is not maintained
